name: Build and Publish Common Library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the Library
        run: mvn clean install

      - name: Deploy to Maven Repository (if applicable)
        run: mvn deploy  # 发布到 Maven 仓库，这里可以配置私有或公共 Maven 仓库
